# Generated by Django 3.1.1 on 2020-11-26 02:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labo', models.CharField(choices=[('0', 'labo'), ('1', 'fujii'), ('2', 'nishikawa'), ('3', 'inoue'), ('4', 'ito'), ('5', 'ma'), ('6', 'kondoh'), ('7', 'tanaka'), ('8', 'tukamoto'), ('9', 'tecd')], default='0', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(0, 0))),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
